apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: court-probation
  labels:
    app: court-probation
spec:
  replicas: 2
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: court-probation-app
  template:
    metadata:
      labels:
        app: court-probation-app
    spec:
      containers:
        - name: court-probation
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/probation-services/court-probation:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: '8000'
            - name: COURT_LIST_URL
              value: 'http://court-list-service:8000'
